#!/usr/bin/env bash
set -o errexit

DOMAIN=${1:-flshop.me}
VERSION=${2:-2.4.7}
EDITION=${3:-community}

curl -s https://raw.githubusercontent.com/datmieu204/flshop/master/lib/template | bash

# &&'s are used below otherwise onelinesetup script fails/errors after bin/download
bin/download "${VERSION}" "${EDITION}" \
  && bin/setup "${DOMAIN}"
